### ISSUE TITLE
[Details Nerdlet] Display different information when the pack has been installed

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-quickstarts#112]
## Description
After the user has installed an Observability Pack, if they go back to the details nerdlet they should see an updated view to reflect the installation status. The following UI elements should be different:

* The install button is no longer present
* The tabs are different: Overview, Support, Documentation
* The overview tab shows tiles that link to the installed items (such as a link to a dashboard)

The designs for this are still a work in progress (why this has a `blocked` label), but have been attached below:

## Screenshot(s)
![Screen Shot 2021-07-16 at 10 22 47](https://user-images.githubusercontent.com/1946433/125986403-50cdb375-6483-4195-a71f-db137d5a6e0a.png)

## Acceptance Criteria
- [ ] Determine if the user has installed the Observability Pack (TBD - perhaps coming from the catalog)
- [ ] Hide the install button
- [ ] Update the tabs to be Overview, Support, Documentation
- [ ] Load links to installed dashboards
- [ ] Load links to installed alerts
- [ ] Display New Relic support information (based on support level) in the support tab
- [ ] Display pack description in documentation tab

**Comment by jpvajda** [comment]
we'll wait on the final design to start this work.

**Comment by jpvajda** [comment]
@kukukaka

**Comment by jpvajda** [comment]
we'll want more clarity on what happens after an install and where the user will be sent to view pack components and access those.

**Comment by jpvajda** [comment]
we will hold off on this screen as it's been decided we won't be attempting to show an installed view of the pack in the marketplace at this time.

**Comment by jpvajda** [comment]
We no longer are responsible for this code as we handed it off to devex, so closing.
