### ISSUE TITLE
[Repository] remove `icon` from schema & API or identifiy a use case for it

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#120]
### Design question

- [x] What was the intention of the icon?
> it's not clear, but since we don't use it anyway let's remove it to reduce the confusing with our contributors and have to support a feature that isn't used.

- [x] What could it be used for in the future?
> it's not clear, but since we don't use it anyway let's remove it. We could always add it back if required. 

The icon is not used in the UIs at this point, and there isn't a clear use case for it yet. So this ticket is just a reminder that we can eventually remove it if it's not needed. 

### Acceptance Criteria

- [x] Ensure there are no UI uses cases where the icon is being used. 
- [x] Remove any icons from packs that may contain an icon
- [x] Remove the icon from the repo docs and templates
- [ ] Remove icon from the schema and API -> `request from Virtuoso`
- [ ] Update repo documentation

**Comment by jpvajda** [comment]
@jbeveland27 just an FYI...

**Comment by rudouglas** [comment]
@jpvajda Do we need to remove this from the Virtuoso Install Service as well?

**Comment by jpvajda** [comment]
@rudouglas if we can do the work, sure or we can request that team to do the change.

**Comment by rudouglas** [comment]
Cool @jpvajda i'll take a look at it to see how much work it might be

**Comment by rudouglas** [comment]
I've done the work on this, just waiting for a review and advice on the order to merge these in https://source.datanerd.us/open-source/open-install-library-service/pull/102

**Comment by jpvajda** [comment]
@rudouglas nice, I added an AC to update all of our repo documentation when this is merged in. 🖇️

**Comment by rudouglas** [comment]
@jpvajda That should already be done, but after chatting to Justin, we may want to mark these as deprecated in the docs first? what do you think?

**Comment by rudouglas** [comment]
Just waiting on the Virtuoso work to be merged https://source.datanerd.us/open-source/open-install-library-service/pull/103

**Comment by rudouglas** [comment]
The Virtuoso work is now merged
