### ISSUE TITLE
[Nerdpack] Dashboard and runbook final touches

### ISSUE THREAD

**Issue by LizBaker** [newrelic/newrelic-quickstarts#126]
Once the nerdpack is deployed to production we can add some final touches to our dashboard and runbook

### Acceptance Criteria 

- [x] Update nrql queries in dashboard with production env (currently they query for _any_ tessen events)
- [x] Update feature flag list in the runbook with production and EU flags
- ~~[ ] Update any feature flags in the runbook with changed names if applicable~~
- [x] Consider if we want more nuanced error charts in the dashboard

### Product Feedback 

- [ ] ensure widgets focused on usage are added to the global Observability Packs: Marketplace Usage Dashboard `https://staging-url-here/-/0GbRmvn8Vjy`
- [ ] any widgets added to this dashboard for the internal usage should be labels `internal:measurement` 
- [ ] any existing widgets that measure external data should be renamed `external:measurement`
- [ ] name the new dashboard used for alerting and troubleshooting `Observability Pack UI: troubleshooting` `https://staging-url-here/-/0PoR8nNLoQG`

**Comment by rudouglas** [comment]
@jpvajda doesn't look like the first dashboard exists anymore, do we have a link to the new one?

**Comment by jpvajda** [comment]
@rudouglas I don't know what dashboard this used to point to, let's ask @LizBaker which one she was referring to in standup today. 🅿️

**Comment by jpvajda** [comment]
My opinion here is since we are handing this off to devex, let's put it in their primary DB called `[DevEx] New Relic I/O`

**Comment by LizBaker** [comment]
@jpvajda @rudouglas  we have a dashboard called [DevnEn] I/O Quickstart detail that has a couple error widgets and a couple usage metrics widgets. I feel like we can call this good, and any other usage metrics widgets folks want in the big dashboard can be put in there. I feel like we can close this ticket
