### ISSUE TITLE
OpenTelemetry quickstart has unhelpful links to GitHub for alerts and dashboards

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/newrelic-quickstarts#1278]
## Description

Please try out this OpenTelemetry yourselves and see if it meets your needs? Here's what I found:

* Why are Dashboard and Alerts sections included if you're not offering any to me?
* Why do you provide buttons under Dashboard and Alerts sections that tease me into thinking there's a useful repository of helpful information. Those **View repo** links just take me to the YML file that contains the same text that appears  in a later section of the quickstart itself! Could you simply remove Dashboard and Alert sections if none are available?
* What is meant by the section heading **Data Sources**? This implies some kind of programming construct or something, but all I see here is a link to the docs.
* The button **Install now** just takes me to the New Relic UI, where it seems like maybe some magic will happen, but alas, I am sent back to the docs. Why not send me to the docs site right off the bat and skip the detours of the fake repo links and the UI?

## Expected Behavior

If I landed on this quickstart from outside the docs site, I'd expect to be taken directly to the docs site to follow the installation routines.

**Comment by clarkmcadoo** [comment]
for ref: https://newrelic.com/instant-observability/opentelemetry/55445c3b-36dc-4bea-b31f-9f82fd551650
