### ISSUE TITLE
[Quickstart Repo] Quickstart logo issues

### ISSUE THREAD

**Issue by tyreer** [newrelic/newrelic-quickstarts#153]
## Description

Some Quickstarts have logo assets that are incompatible with the cards where the logos will be rendered or they aren't rendering well in dark or light mode.

### Design Questions to answer

- [x] Determine who can fix these images?

> marketing offered to assist see the[ asana request](https://form.asana.com/?hash=6cc93328d6651d4247312382a80995cc56bdb6eb9d90b6ed155ef9813e701def&id=1180191231719121)

## image problems

- [cribl logo](https://raw.githubusercontent.com/newrelic/newrelic-quickstarts/v0.32.0/quickstarts/cribl_logstream/logo.svg) doesn't show text in light mode 

![Screen Shot 2021-09-28 at 9 45 33 AM](https://user-images.githubusercontent.com/1395158/135167888-68a08f11-f0c4-4283-ae00-1e3b88ca2a7a.jpg)

- [Trend micro logo ](https://raw.githubusercontent.com/newrelic/newrelic-quickstarts/v0.32.0/quickstarts/trendmicro-cloudone-conformity/logo.png)doesn't show text in dark mode

![Screen Shot 2021-09-28 at 9 45 11 AM](https://user-images.githubusercontent.com/1395158/135168737-f0d62ab5-8e2d-4444-b135-9ceab0895470.jpg)

![image](https://user-images.githubusercontent.com/20293876/130274453-27c2d694-3d52-442f-abf7-3d88ed5cdf74.png)

The problem seems to be either:
- A given logo has a vertical orientation (e.g. 1:2)
- A given logo has vertical whitespace above or below the icon, making it look smaller than it should look

**Logos to replace**:

Vertical orientation
- [x] https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/jmx/logo.png

Whitespace above/below
- [x] https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/consul/logo.png
- [x] https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/memcached/logo.png
- [x] https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/mysql/logo.png
- [x] https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/varnish/logo.png

**Example of a logo that's rendering well and has no excess whitespace**
- https://raw.githubusercontent.com/newrelic/newrelic-observability-packs/v0.10.0/packs/mongodb/logo.jpeg

## Steps to Reproduce

The UI where these tiles render is in development currently. Please contact DevEx in #help-dev-experience if you'd like to reproduce locally or confirm resupplied assets are rendering nicely. Action to resolve this bug should simply be uploading more ratio-friendly assets to replace the problematic icons.

**Comment by nr-kkenney** [comment]
this is probably noise, but as a heads up, we are working on adding more packs to the repo and as part of this work we added ~300 packs, so I've probably made this worse 🙈 

pr for reference: https://github.com/newrelic/newrelic-observability-packs/pull/147

would you happen to have a way to easily check this?

**Comment by tyreer** [comment]
Since those are all SVG logos, I hope we'll be okay actually 🤞 Thanks for the heads up!

![image](https://user-images.githubusercontent.com/20293876/130279495-d546a621-feca-4f41-9a52-d376f11c7e7d.png)

**Comment by tyreer** [comment]
Hm, going through some of those SVGs at random, we might end up with a few that have excess whitespace above/below. Hard to say until they're loaded in the card... But most look good. 

Suppose we'll need to load them up in the UI and assess if any look really off (like the tiny MySQL dolphin 🐬)

https://github.com/newrelic/newrelic-observability-packs/blob/15725c4d73941f1e08eeecb1bdd74132e02e6be8/packs/ansible/icon.svg

https://github.com/newrelic/newrelic-observability-packs/blob/15725c4d73941f1e08eeecb1bdd74132e02e6be8/packs/android/icon.svg

**Comment by jpvajda** [comment]
Dustin Finkle asked me to submit a request to marketing so I did that and targeted it for 10/8.

**Comment by DustinFinkle** [comment]
Got it.  Captured here: https://app.asana.com/0/1200592555863571/1201082122971816/f
I've assigned to Dan Weber on the Creative Team.

**Comment by DustinFinkle** [comment]
@jpvajda , this work? In the zip...

- Horizontal version of the Java logo
- 4 PNG logos with whitespace cropped out
- 2 versions (black and white) of Cribl & Trend Micro
[Quickstart Logos.zip](https://github.com/newrelic/newrelic-quickstarts/files/7269056/Quickstart.Logos.zip)

**Comment by jpvajda** [comment]
@DustinFinkle these should do the trick! we have no good way to test the quickstarts before they actually get updated to the site, but I can make the changes and see how they improve.

**Comment by jpvajda** [comment]
We can't use the dark mode images yet, as we only support one image per quickstart, so this will be a future improvement to consider. https://github.com/newrelic/newrelic-quickstarts/issues/421
