### ISSUE TITLE
Dashboard AJAX & CWV rendering issue

### ISSUE THREAD

**Issue by DarrenDoyle** [newrelic/newrelic-quickstarts#1692]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When installing the Browser Ajax Requests & Core Web Vitals Quickstart dashboards onto accounts, a number of widgets won't fetch the data

## Steps to Reproduce

1.  Go to add data 
2. Dashoards -> Browser Ajax Requests & Core Web Vitals Quickstart
3. Install 

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
Widgets in the Dashboard display the data

## Actual Behavior
Receive this error We couldn't fetch this data
 <img width="835" alt="Screenshot 2023-03-15 at 09 27 21" src="https://user-images.githubusercontent.com/12893310/225266456-d8e085dd-cab0-47ae-9436-49b108ad0bec.png">

## Additional context
I'm thinking it could be of two things 

1. Some queries have Regular Expressions 
2. The accountid are being referenced like this "accountIds": [
                  0
                ],

**Comment by harrykimpel** [comment]
> 

@DarrenDoyle I just installed the dashboard in my account with a standard Browser entity reporting. All widgets work fine in my account.
