### ISSUE TITLE
[I/O] ⭐️ Improved Search Sort & Filter + SSR

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-quickstarts#187]
## Epic Milestones

- An upcoming MMF for DevEx (OCT) will focus on replacing client side search and moving the filter/ search logic to a backend service. this service will support popularity, relevance and reverse alpha sort.
- User accepted ratings won't be exposed yet in the UI, but the service will sort on popularity based on install data. Later on we could accept user ratings if we feel it's required.
- DevEn will need to upgrade to Gatsby 4 which has SSR, THEN we can possible leverage this new service built by DeVex 
- New fields will be available in nerdgraph, under product [experimental].

## Epic Plan

https://docs.google.com/document/d/1jerufX6qOaOGnuZCtZwoSNBNdxux0CTngeFH_uXZmoU/edit#

## Captain 

@aswanson-nr

**Comment by jpvajda** [comment]
extended end date of this epic as this is blocked by this lack of functionality of Gatsby Cloud not supporting private environment variables.

**Comment by jpvajda** [comment]
extending the timeline of this epic 2 more weeks  as this is blocked by this lack of functionality of Gatsby Cloud not supporting private environment variables. ETA for that feature is ~ `Jan 24th`

**Comment by jpvajda** [comment]
We are going to hold off on this, until we can wrap up the localization epic and re-arch work.
