### ISSUE TITLE
 Hero bot setup for `#help-newrelic-io`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#212]
Proposed for GA: Each team provides hero coverage and take issues that relate to their areas
Hero teams: DevEn, Virtuoso, DevEx, DevAdvocacy 

### 🤖 information

- We have 2  bots we can use `helpbot` or `alias`. 
- all alias does is let you set a term (like @hero or @team with a set of people to tag, you can have multiple terms. helpbot just has @hero and can be associated with one channel per team. which is why we have it in demotron but not help websites or any of our other channel

### Acceptance Criteria 

- [ ] could we use workflows in slack to post a message? 
- [ ] confirm approach with cross functional team @jpvajda 
- [ ] Determine a logical hero rotation as this spans multiple teams.  The main hero on rotation handles the routing to other teams.
- [ ] Set up multiple heroes on alias! to ping the individual heroes on each team to cover their area.

**Comment by aswanson-nr** [comment]
The approach will use aliases to notify teams and information in the channel topic.
The doc is located in the team shared folder at `I Need a Hero (Hero Docs) > I/O Hero rotation`
