### ISSUE TITLE
Set SLO / SLI metrics for I/O External Site and quickstarts Repo 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#213]
We've been ask to provide SLI/ SLO metrics for the I/O external site and open source contributions to the repository. 

### Ideas

**Site Uptime: 99.99%**

-  Daily: 8s
-  Weekly: 1m 0s
-  Monthly: 4m 22s
-  Quarterly: 13m 8s
-   Yearly: 52m 35s

**Contributor response time:**

- first response to PR in 24hrs 
- time to merge a PR: 
> variable, due to contributor availability hard to set a metric , but let's go with 7 days based on the current speed we are merging contributions and we can adjust from there.
- time to close a pr: 
> variable, due to contributor availability hard to set a metric , but let's go with 7 days based on the current speed we are merging contributions and we can adjust from there.

**lighthouse metrics**

- Can we bring in lighthouse metrics into new relic for dev site performance? - [Article](https://newrelic.com/blog/how-to-relic/monitoring-with-google-lighthouse)

### Acceptance Criteria

- [x]  Define the SLI/SLO metrics that make sense for these experiences 
- [x] Confirm how we can measure if we are meeting these metrics
- [x] Setup dashboards to track these metrics.
     - [x] Site Uptime
     - [x] Contributor Response Time
     - [x] Time to Merge PR
     - [x] Time to Close PR (This should probably just be Merge/Close)
     - [x] LightHouse Metrics

**Comment by jpvajda** [comment]
I'll take a pass at this to confirm what we want to track for GA.

**Comment by rudouglas** [comment]
I've been playing around with this a little and have come up with some solutions that would could leverage, i'll chat about them in standup

**Comment by rudouglas** [comment]
oh i actually managed to calculate the days a PR was opened for before it was closed using sub-aggregation, this is in the `[DevEn] External I/O & Quickstarts Ecosystem` as well, the only thing is we can't do much else with the data, and can only format it in a table, i think a custom viz would be ideal but

**Comment by rudouglas** [comment]
The github time to close should also probably only include contributor PR's so we may need to use labels to identify those
