### ISSUE TITLE
Create an Uber Dashboard for QuickStarts Deven Ecosystem data

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#216]
There are several dashboards being used for Quickstarts, let combine those into one uber dashboard that is the one stop place to go for all things quickstarts for DevEn.

### Acceptance Criteria

For links to dashboards see `g-drive` `Observability Packs: Production Readiness`
- [ ] Make one uber dashboard (similar to NR1 Ecosystem dashboard) that combines these dashboards created during development: DB1 & DB2  into one dashboard that accounts for the entire olly pack ecosystem. 
- [ ] DB3 is a nice dashboard created by devex
- [ ] We can use DB1 as the primary dashboard and the widgets we need.
- [ ] Can we get a count of what quickstarts contain installlPlans?
- [ ] Can we get a count of what quickstarts contain what type of components? alerts, dashboards, etf

**Comment by jpvajda** [comment]
and so it begins...

**Comment by polfliet** [comment]
FYI [Here](https://github.com/polfliet/newrelic-observability-packs/blob/import-scripts/utils/scripts/checkQuickstarts.py) is the python script I used to get some counts
