### ISSUE TITLE
Code related updates for `Observability packs` to `quickstarts` rename

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#228]
## Description
Various code updates for the rename to `quickstarts`.

## Acceptance Criteria
- [ ] Notify the Partner Team that we'll be changing the repo name and structure so they aware. - @jpvajda 
- [ ] This repository is renamed to `newrelic-quickstarts`
- [x] The `/packs` folder is renamed to `/quickstarts`
- [x] @jbeveland27  is updated on repository rename and folder rename, we could also submit a PR!
- [x] Workflows and related files are updated, including those under the `/utils` directory
- [x] Add a blurb to the top of the readme to let contributors know about the rename

**Comment by nr-kkenney** [comment]
at the end of this, we may want to confirm things still work in the io site if this isn't verified a long the way. we can still view packs, confirm that they link to the correct place in github, etc.

**Comment by rudouglas** [comment]
I did 2 separate PR's for this, the first is our code, documentation and filenames. The second is changes to the importer which will need to be tested apres merge

**Comment by rudouglas** [comment]
1. #283 
2. #284 
3. #287

**Comment by jbeveland27** [comment]
@rudouglas The newrelic-cli is now decoupled from o11y packs, so we're good to move forward with renaming the repo.

**Comment by jbeveland27** [comment]
> Notify the Partner Team that we'll be changing the repo name and structure so they aware.
@jpvajda One minor thing to be aware of (in case you weren't already) - once the repo is renamed, I believe existing forks stop working (i.e. they can't PR back to the original repo). Those partners will need to re-fork. So if there's any in-progress work, they should just be aware that they might need to copy it over to a new fork.
