### ISSUE TITLE
Add featured keyword to partner packs

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#244]
Stijn will  make a PR once we have all of the partner  PRS quickstarts merged in.

### Acceptance Criteria 

- [ ] Add `Featured` keyword to: Kentik, Lacework, Trend Micro, Fastly, Cribl Quickstarts
- [ ] Confirm with Buddy or Jemiah how we'll be handling the rotation of featured packs manually.

**Comment by jpvajda** [comment]
@polfliet did you have this on your TODO list? did you need help?

**Comment by polfliet** [comment]
Waiting for the final PR from Lacework, but the others were added: https://github.com/newrelic/newrelic-quickstarts/pull/373/files
