### ISSUE TITLE
[Details Nerdlet] Missing support information on quickstart details page

### ISSUE THREAD

**Issue by polfliet** [newrelic/newrelic-quickstarts#277]
## Description
The public experience shows details on how to get support for a specific quickstart.
This information is not shown in the in-product view.
For an example see the Node.js quickstart.

The public version contains the below snippet summarizing how to contact support.
![Screenshot 2021-09-19 at 14 38 45](https://user-images.githubusercontent.com/45029322/133927815-e66c136a-d369-4c8a-909e-83f8c75913ae.png)
This is missing from the in-product view

## Steps to Reproduce

* Click on the Node.js tile and go to the quickstart details page
* The authors are shown, but there is no

## Expected Behavior

* The support information is shown in a right rail under the screenshots in product 
* The author information is also present in the same right rail under the screen shot.

**Comment by rudouglas** [comment]
@polfliet @jpvajda I wasn't 100% sure where this should go, the Authors + Support are in the right rail in the Public Catalog, but the Authors are at the bottom of the page in Product, which do you prefer?

<img width="1785" alt="Screenshot 2021-09-21 at 12 19 15" src="https://user-images.githubusercontent.com/17122543/134162936-b8ec22fd-5962-4743-ada4-034d3c4ca574.png">
<img width="1786" alt="Screenshot 2021-09-21 at 12 29 25" src="https://user-images.githubusercontent.com/17122543/134162948-68714da3-3479-487c-9401-aac58e0a36ad.png">

**Comment by polfliet** [comment]
@rudouglas I would vote for keeping it consistent with the public site and showing both the Authors and Support level in the right rail

**Comment by rudouglas** [comment]
excellent thaaaank you sirs

**Comment by rudouglas** [comment]
<img width="1915" alt="Screenshot 2021-09-22 at 12 29 23" src="https://user-images.githubusercontent.com/17122543/134336950-7fb12422-d546-4a09-9aaa-13841b8e2696.png">

**Comment by jpvajda** [comment]
Since we removed the right rail we dropped this below authors, I  will check with @danielgolden if this works for now.

**Comment by jpvajda** [comment]
@danielgolden confirmed we can put this back under the screen shot in a mini right rail. so perhaps we take the original approach and just place a div with the content in it, with a border around it? @rudouglas 


<img width="472" alt="Screen Shot 2021-09-22 at 4 03 24 PM" src="https://user-images.githubusercontent.com/1395158/134428254-306acd4f-5a1f-4fde-b18b-3234de799eda.png">

**Comment by jpvajda** [comment]
Mock up: 🎨 🧑‍🎨 
<img width="1912" alt="details" src="https://user-images.githubusercontent.com/1395158/134428597-a9a7c2bc-7ee6-4f4c-ab7c-a4ffad277fbc.png">

**Comment by jpvajda** [comment]
Let's also move authors back over with support as well since we are adding this back into the design. I think it makes a lot more sense under support like we have on the external site.

**Comment by aswanson-nr** [comment]
@rudouglas Could you add an estimate to this when you get a chance?

**Comment by rudouglas** [comment]
Yessir, this is the updated styling

<img width="1913" alt="Screenshot 2021-09-23 at 12 02 52" src="https://user-images.githubusercontent.com/17122543/134496478-e307ee82-5648-45dd-9c20-13b252ebc1f9.png">
<img width="1916" alt="Screenshot 2021-09-23 at 12 03 27" src="https://user-images.githubusercontent.com/17122543/134496498-ee49d77b-5c4b-4945-8397-c5406d745fa7.png">

**Comment by jpvajda** [comment]
@rudouglas can dial back those headers on Support /Author - should be same as screenshot just [scope how the external catalog handles it, should be simila](https://observabilitypacks.gatsbyjs.io/instant-observability/dotnet/2dff13b6-0fac-43a6-abc6-57f0a3299639)r

**Comment by rudouglas** [comment]
@jpvajda how dis look
<img width="535" alt="Screenshot 2021-09-24 at 13 48 13" src="https://user-images.githubusercontent.com/17122543/134676733-c3d4e568-1759-49c2-be3d-9f974da9cbe3.png">

**Comment by jpvajda** [comment]
looks great, I commented on the PR on a conflict in the constant.js file.

**Comment by rudouglas** [comment]
@jpvajda sweet thanks conflict is now resolved 🎊
