### ISSUE TITLE
[Quickstarts Repo] provide Quickstart preview functionality

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#330]
`Problem:` a contributor has no easy to preview a quickstart development. 

- Requires all teams to consider the approach
- Sounds like a pretty complex problem
- There are architecture discussions and changes we have to consider. 

### Key functionality 

- need to preview the external experience and how it will look on the external site
- need to preview the internal experience and how it will look on the internal site 
- need a way to validate if it will install correctly

**Comment by jpvajda** [comment]
What is being discussed for architecture around this @aswanson-nr ?

**Comment by nr-kkenney** [comment]
@jpvajda does this also include validating the components like dashboard, docs? or just the site and the experience?

**Comment by jpvajda** [comment]
closing as this is becoming an epic.
