### ISSUE TITLE
[Details Nerdlet] add separators between component types on the overview tab

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#338]
### Issue

the design called for separators between the component types on overview tab.  

### Steps to reproduce 

Go to an quickstarts overview tab and you'll see:

<img width="1867" alt="Screen Shot 2021-09-23 at 11 44 45 AM" src="https://user-images.githubusercontent.com/1395158/134558030-a7e2e78e-7863-4a90-9886-b981c478cfd2.png">

when you should see...

![Screen Shot 2021-09-23 at 11 44 52 AM](https://user-images.githubusercontent.com/1395158/134558067-8a6dbe96-97e4-49bc-bcb0-a08066707008.png)

### Expected

component separators are visible

**Comment by LizBaker** [comment]
@jpvajda whoops, we had this design in place but it looks like alec changed it so that it looked the same at the public version. ironically I approved that PR :D, i'll swap it back
