### ISSUE TITLE
[Details Nerdlet] spacing and header alignment

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#340]
The rendering of headings, paragraphs and the spacing between them should be more organized. Probably too detailed to write down here (let’s have a conversation about this). As an example, we should render h1s and h2s as h3s, maximum.

**Comment by jpvajda** [comment]
PR: catalog-pack-details/pull/49

**Comment by jpvajda** [comment]
This looks good and is now merged in

**Comment by danielgolden** [comment]
Is this in production already?

**Comment by jpvajda** [comment]
@danielgolden it's all on staging now.
