### ISSUE TITLE
[Quickstarts API] null dashboard descriptions

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#356]
Dashboard's are exported from the product with a `null` value for an empty description instead of an empty string. Currently we restrict this to a required empty string and to reduce friction for contributors, we would like to allow dashboard descriptions to be null.

Relates to `JIRA` `Virtouso-1382`

### Acceptance Criteria

- [x] confirm `Virtouso-1382` is completed
- [ ] Make changes to validation schema to allow `null` or `string` for descriptions

**Comment by rudouglas** [comment]
Dashboard Json when exported from the platform can have `null` values for `description` fields par example:

```
{
    "name": "Apache",
    "description": null,
    "pages": [
        {
            "name": "Apache",
            "description": null,
            "widgets": [
                {
```

We are enforcing that in the [schema](https://github.com/newrelic/newrelic-quickstarts/pull/377/files) but want to allow `null` to make contributor flow more streamlined. Checking with Virtuoso if this will affect anything on their end

**Comment by aswanson-nr** [comment]
From our discussion in standup today, let's keep this in PR until after the launch.

**Comment by rudouglas** [comment]
The Virtuoso work is now complete, but this also won't affect things on our side so we are able to leave this work until post-launch if we need

**Comment by jpvajda** [comment]
@rudouglas let's discuss the risk, and impact by introducing this change in 🅿️

**Comment by jpvajda** [comment]
🚢 🇮🇹
