### ISSUE TITLE
Create a dashboard for quickstart component counts

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#366]
We want to be able to visualize data for quickstarts components answer questions such as:

- What quickstarts `contain` dashboards and /or alerts and `contain` targeted install?
- What quickstarts `contain` dashboards and /or alerts but `do not contain` a targeted install?
- What quickstarts `do not contain` dashboards and /or alerts and `contain` a targeted install?
-  What quickstarts `do not contain` dashboards and /or alerts and `contain` a documentation reference?

This data is in NerdGraph, but I don't think it's going to be available in a NRQL query (it's not something that's in NRDB)

### ideas

- Setup a custom visualization data to display this data
- product-ionize @polfliet [python script ](https://github.com/polfliet/newrelic-quickstarts/blob/import-scripts/utils/scripts/checkQuickstarts.py)and add it `utils` directory so we can quickly run it when needed. -> Convert to javascript.
- set up a GH action that uses Stijn's python script and then use our APIs to push the data into NRDB. Run it once every day. Then you can dashboard it
- If we turn this into data we can pull into a dashboard @jpvajda has an Quickstart ecosystem dashboard we can put this in. 

### a visual 🎨 

<img width="1794" alt="Screen Shot 2021-09-24 at 9 14 25 AM" src="https://user-images.githubusercontent.com/1395158/134707182-bb0f7a5e-bedf-40ad-82b9-23b4ea7a91c2.png">

### Acceptance Criteria 

- [ ] build a custom (internal only) viz nerdpack  (Devex can help if we need pointer as they built custom viz)
- [ ] make opensource experimental project
- [ ] add the custom viz to our ecosystem dashboard.

**Comment by rudouglas** [comment]
Story so far...
<img width="1781" alt="Screenshot 2021-09-29 at 13 22 56" src="https://user-images.githubusercontent.com/17122543/135267866-e699e61f-41ff-44e0-bdb6-66916efafbea.png">

**Comment by jpvajda** [comment]
YES. @polfliet  ^^

**Comment by jpvajda** [comment]
@rudouglas how hard would it be to add this to our ecosystem dashboard? I guess if it's a nerdpack, we can display the content, but I can link to where the nerdpack is available. 🤔
