### ISSUE TITLE
[In Product I/O] Support dark mode / light mode images for quickstart logos

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#421]
given our lighter darkmode tone `#1C2A2F` on the external site this isn't a big issue for us. 

### Issue

Internally several quickstarts have logos that don't look good in dark mode.

### Considerations

- One idea was to make the background of a tile a gray tone, then it would compliment an image that doesn't work as well n different modes better, but they would definitely impact the ascetic. 
- Another idea, is to use a lighter dark mode as in product it's very dark. 

### Design Approach

The main changes are:
- Add white background to logo image wrapper.
- Apply brightness and contrast filter to image tag => `filter: brightness(.8) contrast(1.2);`
- Add vertical spacing on the logo image wrapper => `padding: 12px inherit` 
- Add round border around logo image wrapper => `4px`

On the long run
There are better approaches to this that have been explored from the design side but they will be implemented in future iterations.

Figma file for the change: https://www.figma.com/file/943wgfsvJwRtwp0lxcRlW3/?node-id=6209%3A252332

Figma file for the path long run: https://www.figma.com/file/943wgfsvJwRtwp0lxcRlW3/?node-id=51%3A77385 

## image problems

- [cribl logo](https://raw.githubusercontent.com/newrelic/newrelic-quickstarts/v0.32.0/quickstarts/cribl_logstream/logo.svg) doesn't show text in light mode 

![Screen Shot 2021-09-28 at 9 45 33 AM](https://user-images.githubusercontent.com/1395158/135167888-68a08f11-f0c4-4283-ae00-1e3b88ca2a7a.jpg)

- [Trend micro logo ](https://raw.githubusercontent.com/newrelic/newrelic-quickstarts/v0.32.0/quickstarts/trendmicro-cloudone-conformity/logo.png)doesn't show text in dark mode

![Screen Shot 2021-09-28 at 9 45 11 AM](https://user-images.githubusercontent.com/1395158/135168737-f0d62ab5-8e2d-4444-b135-9ceab0895470.jpg)

**Comment by jpvajda** [comment]
relates to: #153

**Comment by legnaleama** [comment]
This is not the most elegant solution but it achieves the main 2 objectives for the release:
- Fixes readability
- Standardises look&feel for logos on both Light and Dark mode

The main changes are:
- Add white background to logo image wrapper.
- Apply brightness and contrast filter to image tag => `filter: brightness(.8) contrast(1.2);`
- Adds vertical spacing on the logo image wrapper => `padding: 12px inherit` 

On the long run
There are better approaches to this that have been explored from the design side but they will be implemented in future iterations.

Figma file for the change: https://www.figma.com/file/943wgfsvJwRtwp0lxcRlW3/?node-id=6209%3A252332

Figma file for the path long run: https://www.figma.com/file/943wgfsvJwRtwp0lxcRlW3/?node-id=51%3A77385
