### ISSUE TITLE
[Repository] Add a quickstart logo PR review check

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#498]
## Summary
Since we already have a [job](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml#L70) in place to validate that an image exists if it is referenced in the `config.yml`, we can just mark this as a required field in the JSON schema and the rest of the automation will take care of it.

### Acceptance Criteria

- [x]  do an audit for missing logos and make a list so we can get a content person to assist, report back to @jpvajda the count to move forward, then review with @bradleycamacho to understand how to update the logos.
- [x]  Update the [required fields](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/schemas/main_config.json#L46) to include the `logo` field
- [x]  If no logo is present show the user a failed check and specify how to resolve the issue
- [x] ~~Update [main config docs ](https://github.com/newrelic/newrelic-quickstarts/blob/main/docs/main_config.md) as a logo is now going to be required~~ This file is auto generated from the schema, so it will be updated automatically
- [x] Update [contributor guide ](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#logos)to explain a logo is required.

**Comment by rudouglas** [comment]
I wrote a script you can run to check for any quickstarts missing logos.

```
cd utils
node check-missing-logos.js
```

Here's the list of quickstarts with missing logos:
```
[
  'quickstarts/account-data-ingestion/config.yml',
  'quickstarts/aws/aws-elemental-mediapackage-vod/config.yml',
  'quickstarts/aws/aws-fsx/config.yml',
  'quickstarts/aws/aws-outposts/config.yml',
  'quickstarts/aws/aws-x-ray/config.yml',
  'quickstarts/azure/azure-power-bi-dedicated-capacities/config.yml',
  'quickstarts/browser/config.yml',
  'quickstarts/dotnet/iis/config.yml',
  'quickstarts/dotnet/umbraco/config.yml',
  'quickstarts/full-story/config.yml',
  'quickstarts/golang/gin/config.yml',
  'quickstarts/golang/lambda-go/config.yml',
  'quickstarts/golang/logrus/config.yml',
  'quickstarts/golang/logxi/config.yml',
  'quickstarts/golang/micro/config.yml',
  'quickstarts/golang/mux/config.yml',
  'quickstarts/golang/nats/config.yml',
  'quickstarts/golang/zap/config.yml',
  'quickstarts/infrastructure/config.yml',
  'quickstarts/java/asynchttpclient/config.yml',
  'quickstarts/java/websphere-liberty-profile/config.yml',
  'quickstarts/lamp/config.yml',
  'quickstarts/node-js/hapi/config.yml',
  'quickstarts/okhttp/config.yml'
]
```

**Comment by jpvajda** [comment]
@rudouglas nice! could this be called via a Github action on the submission of a PR

` If no logo is present show the user a failed check and specify how to resolve the issue`

**Comment by rudouglas** [comment]
@jpvajda this should already be part of the Schema compliance check so will tell the user if a logo is missing

**Comment by rudouglas** [comment]
@jpvajda it might be better to keep this as a separate branch for now. Currently, it will fail the schema checks because of all the missing logos, so keeping it separate will allow the content team to work on it, run the script to check for the missing logos until they are all complete, then we can merge into main:

https://github.com/newrelic/newrelic-quickstarts/tree/ru/logo-check

What thinkest thou?

**Comment by jpvajda** [comment]
💯  @rudouglas let me checkin with @bradleycamacho on who can help source new logos until we have those in place let's keep this in it's own branch as you suggested. Here is a follow up ticket I'll work on to get the missing logos into the quickstarts repository 

https://github.com/newrelic/newrelic-quickstarts/issues/562

**Comment by zstix** [comment]
We have a follow-up ticket to add the logos themselves. There's a branch that we're going to merge in once those have been added.
