### ISSUE TITLE
☂️  Support for variables in Quickstarts

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-quickstarts#52]
## Summary

It would be really helpful to be able to reference variables / secrets for an entity / account when configuring components of an observability packs. A great example would be the URL for a browser entity (for synthetics scripts).

`OR` 

Have a variable substitution when creating/installing a quickstart? For example if I wanted to add a `WHERE appId = <value>` to some of my queries, is there a mechanism for the user to specify` <value>` during installation.

Without this feature, we had to close #39

### Other variable uses cases

`1` We've identified several use cases where being able to add a variable to a quickstart to allow that to be set by a user on installation would be really nice. 

One example is the when using the netlify quickstart 

 - 1. Supply just an app name and a New Relic user key
- 2. Supply the required ids/keys (the current method)
 
`2` Another is variables required in synthetic checks
 
`3` And there are likely many others. like setting 3rd party API keys, env variables, or license keys for access to services that a quickstart could integrate with.

## Desired Behavior
Some mechanism for referencing variables that are set at an entity (or account) level. I believe there is already support for something like this in the platform, but I'm not sure on the level of effort needed to implement it.

## Possible Solution
We could perhaps use variables with some sort of interpolation syntax like `${{some_var}}`

```yml
name: Failed Signups
type: BASELINE
nrql:
  query: "SELECT count(*) FROM JavaScriptError WHERE pageUrl = "${{env.signup_page_url}}"
```

**Comment by jpvajda** [comment]
💯
