### ISSUE TITLE
IBM MQ dashboard doesn't import

### ISSUE THREAD

**Issue by nedl86** [newrelic/newrelic-quickstarts#543]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The dashboard in the IBM MQ quickstart doesn't import. Error is below.

## Steps to Reproduce

Install quickstart for IBM MQ. Dashboard import fails with error "Error: the mutation failed, please try again".

## Expected Behavior

Dashboard should be able to import.

## Relevant Logs / Console output

``
{"data":{"openInstallationQuickstartInstall":{"__typename":"OpenInstallationQuickstartInstallResult","alerts":{"__typename":"OpenInstallationQuickstartAlertCreateResult","alertConditions":null,"alertPolicy":null},"dashboards":[],"errors":[{"__typename":"OpenInstallationQuickstartResultError","componentName":"IBM MQ PROD","componentType":"DASHBOARD","description":"error creating dashboards: [Error | An error occurred resolving this field]","type":"DASHBOARD_CREATE_ERROR"}]}}}
``

## Additional context

Replicated on multiple New Relic accounts.

**Comment by nedl86** [comment]
Note: I _think_ it's the linkedGuids and description attributes - both should be `null` in all occurrences.

**Comment by hsinghkalsi** [comment]
@psomareddy

**Comment by jpvajda** [comment]
When trying to import the dashboard JSON in this quickstart to new relic I get this error:

```
Heads up! We updated our JSON code to the Dashboards Public API JSON Schema. Please update your templates.

```

**Comment by jpvajda** [comment]
@thezackm helped me out he's 💯 🥇
