### ISSUE TITLE
[Repository] Add code owners

### ISSUE THREAD

**Issue by MoonlightKomorebi** [newrelic/newrelic-quickstarts#554]
## Summary
Similar to the work done in https://github.com/newrelic/docs-website/issues/3658, we want to setup code owners for this repository to delegate PR review assignments to GitHub.

In combination with [code review assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team), this should help smooth out our process for getting through PRs.

## Acceptance Criteria
- [ ] Setup dev-enablement as code owners for `.github`, `utils`, and other import directories and files

## Links
- [Code Owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
- [Code Review Assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team)

**Comment by jpvajda** [comment]
I like this idea and brought it over to tentative next to discuss in a backlog review session
