### ISSUE TITLE
[Repo Rearchitecture] improve error output when permissions field is present in dashboard json

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/newrelic-quickstarts#557]
## Summary
Many PRs have run into this issue where a dashboard.json is updated and the permissions field is included in the json file. That file is explicitly required to NOT be included, so contributors have to remove it. However, the check output doesn't make this requirement clear.

```none
Error: quickstarts/mlops/superwise/dashboards/superwise.json
	 '#/not' must NOT be valid
	 '#/additionalProperties' must NOT have additional properties
```

[Example](https://github.com/newrelic/newrelic-quickstarts/runs/4170892767?check_suite_focus=true)

The code where this runs can be found in [utils/validate_quickstarts.js](https://github.com/newrelic/newrelic-quickstarts/blob/907e245f385900c8dcb1e77ba7a774e68b44c5b5/utils/validate_quickstarts.js#L32) `convertErrors` method which constructs the error message we ultimately see in GitHub.

## Acceptance Criteria
- [ ] improved error output when a dashboard.json file has `permissions` field included
  - at the very least, the output should point to what field needs updating. in this case, `permissions` should be somewhere in the output.

**Comment by jpvajda** [comment]
essentially what we are trying to say is: 

You should not have any line with a value for permissions even if empty.

**Comment by jerelmiller** [comment]
FYI, the new service will have a message like the following:

```
`permissions` must not be set
```

Not sure if this is descriptive enough, but hopefully its a bit easier to parse than what's currently there.

**Comment by jpvajda** [comment]
@jerelmiller that will definitely help!

**Comment by jpvajda** [comment]
@jerelmiller so when we finish the migration to the catalog service and the re-arch epic, we can probably mark this as done?

**Comment by jerelmiller** [comment]
Yes!

**Comment by jpvajda** [comment]
When we finish the the repo-re arch epic, we can validate this is in place, but it should resolve this problem.

**Comment by jpvajda** [comment]
closing as @aswanson-nr said this is in place
