### ISSUE TITLE
[Repo Rearchitecture] Use DevEx service to create new and update existing quickstarts

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#567]
### Description

⚠️  This will not replace the current process yet, but will rather work in parallel with the new system so new workflows should be created for this work

Quickstarts will be created/updated via NerdGraph.

We will use the `submitQuickstart` endpoint to update the data for that quickstart. The endpoint will return the quickstart details but it may also return errors so we need to be able to handle them effectively. We will need a list of potential errors returned by the endpoint and implement things like retry logic etc.

We will also need to take into account our 3 environments which will need to be released at the same time:
 - EU production
 - Production
 - Staging

NOTE: This will not replace the current process yet, but will rather work in parallel with the new system so new workflows should be created for this work

### [Job-generate-release](https://github.com/newrelic/newrelic-quickstarts/blob/832f28ca88b23e5bd678019340b02c58d34037f9/.github/workflows/release.yml#L190)

 - New Job/Script needed
    - `update-quickstart` - This should be in [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/release.yml) and run the new script

### Acceptance Criteria

- [x] DevEx will have a [fork](https://github.com/newrelic/newrelic-quickstarts/pull/665) this functionality we want to confirm is available prior to starting this work.
 - [x] Create a new Job in the [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/release.yml) that runs a new script ~`update-quickstart`
 - [x] The script should identify an updated quickstart when the `config.yml` has an existing `id` field.
 - [x] Should send the configuration details to the DevEx `submitQuickstart` NerdGraph endpoint
 - [x] Should handle errors returned from the service
 - [x] Should include unit tests

#### Helpful Links

Schema - https://docs.google.com/spreadsheets/d/1EmAvq4kJUUPlpvJZ-s23uKDk_KCws9VgHzG1bJtwE4Y/edit#gid=0
NerdGraph - https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20nr1CatalogSubmitMetadata%0A%7D%0A
DevEx Service - https://source.datanerd.us/nr1-dev-experience/catalog-service-elixir

**Comment by rudouglas** [comment]
This is currently blocked by Virtuoso's planned work to add a `dryRun` argument to queries in order to validate quickstarts

**Comment by jpvajda** [comment]
From this [comment](https://github.com/newrelic/newrelic-quickstarts/issues/631#issuecomment-992745503) it sounds like there are few changes to the approach @rudouglas

**Comment by rudouglas** [comment]
I've added info for our 3 different endpoints and the changes Jerel mentioned so this may need to be repointed

**Comment by tyreer** [comment]
For immediate purposes can use `updateQuickstart` since `submitQuickstart` is not yet stitched. The 2 mutations will have the same shape / input

**Comment by jpvajda** [comment]
I confirmed with @jerelmiller, this isn't blocked. 

_We should be ok to finish all work on DevEn side regardless of the status of the service, as long as we don’t yet switch to using the service as the primary means of deploying/validating_
