### ISSUE TITLE
[Repo Rearchitecture] Update public GitHub PR process to use catalog service mutations for validating data

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#571]
## Description

⚠️  This will not replace the current process yet, but will rather work in parallel with the new system so new workflows should be created for this work

The current GitHub PR process uses custom validation scripts to ensure the data is accurate and built correctly. We want to try and leverage the catalog service to perform the validations instead so that as we make tweaks and/or have new data requirements, we make changes in a singular place.

The virtuoso team is working on the mutations right now and will provide a `dryRun` argument for the `submitQuickstart` endpoint. Once https://github.com/newrelic/newrelic-quickstarts/issues/631 is complete we will be able to use this mutation.

### [Validate-packs](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)
 - Jobs/Scripts we will need to change to use NerdGraph
      - [Ensure-schema-compliance](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/validate_packs.yml#L6)
          - Script: [/utils/validate_quickstarts.js](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/validate_quickstarts.js)
      - [Ensure-quickstart-names-ids-are-unique](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/validate_packs.yml#L24) (ID check will not be needed once this is being generated in the NerdGraph Service)
          - Script: [/utils/check_quickstart_uniqueness.js](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/check_quickstart_uniqueness.js)
 - Waiting for clarification on what other validation this will replace

## Acceptance Criteria
- [ ] Update validation script to be _able_ to run against all quickstarts, but _only_ run against the updated quickstarts at PR time
- [ ] Quickstart validation should now be done via either `create` or `update` endpoints using a `dryRun` argument. https://github.com/newrelic/newrelic-quickstarts/issues/631 will determine which endpoint to send to
- [ ] Update [Ensure-schema-compliance](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/validate_packs.yml#L6) job to remove most validation except logos exist and images are the right format
- [ ] Update [/utils/validate_quickstarts.js](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/validate_quickstarts.js) to send data to GraphQL endpoint and receive response and report the success / failure reason back in the workflow
- [ ] Consider whether or not to remove [Ensure-quickstart-names-ids-are-unique](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/validate_packs.yml#L24) job (ID check will not be needed once this is being generated in the NerdGraph Service). _NOTE: The catalog service is not able to check for uniqueness on its own, so we may want to leave this check in place_
- [ ] Remove [/utils/check_quickstart_uniqueness.js](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/check_quickstart_uniqueness.js) script
- [ ] Update the error messages that come back when validating PRs
- [ ] Update unit tests for the PR validation code

### Helpful Links
Schema - https://docs.google.com/spreadsheets/d/1EmAvq4kJUUPlpvJZ-s23uKDk_KCws9VgHzG1bJtwE4Y/edit#gid=0
NerdGraph - https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20nr1CatalogSubmitMetadata%0A%7D%0A
DevEx Service - https://source.datanerd.us/nr1-dev-experience/catalog-service-elixir

**Comment by jpvajda** [comment]
@rudouglas will clarify what files are changing to define the AC better
