### ISSUE TITLE
[Dashboard] How can we report on quickstart contributions? `new` vs. `improved?`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#574]
When attempting to report on our key results for I/O relating to quickstart contributions, I can only pull this data manually. Is there a way to create a dashboard component that could report this data:

- Created new quickstarts per quarter
- improved  existing quickstarts per quarter

### Ideas

1. @rudouglas made a custom visualization which can report on a lot of useful quickstart data, perhaps we can add to that custom viz? [see this dashboard](https://staging.onenr.io/0x0jlXM1MjW)

2. We pull in a lot of github activity into dashboards, but how can we tell if a PR is new functionality vs. improving existing functionality? 🤔

**Comment by jpvajda** [comment]
@rudouglas --> the mad science continues... 🧑‍🔬 _evil laugh_

**Comment by jpvajda** [comment]
> we could use automation to add new or updated labels depending on whether a config.yml

that could work..

**Comment by jpvajda** [comment]
you are the best! 🚀

**Comment by jpvajda** [comment]
I've added this our ecosystem dashboard.

**Comment by rudouglas** [comment]
I'll do some busy work next week adding those labels retrospectively
