### ISSUE TITLE
[Repository] add a check to ensure a quickstart directory name follows our conventions

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#603]
we had an issue where the directory name for this[ quickstart](https://github.com/newrelic/newrelic-quickstarts/pull/602/files) was set to `Jumpstart - Quickstart`, which is invalid as it breaks when we load the quickstarts into our service. The directory should be lowercase-hyphenated.

### Acceptance Criteria  

- [ ] Add a check so we can check to make sure the directory name is set correctly to `lowercase-hyphenated.`

**Comment by jpvajda** [comment]
@aswanson-nr I'm curious if this is now enforced by the catalog service, and this is no longer a concern for the repo. What do you think?

**Comment by jerelmiller** [comment]
This would not be handled by the catalog service since the catalog service is unaware of the repo structure. This would need to be handled repo-side to enforce a particular repo structure.

**Comment by jpvajda** [comment]
@jerelmiller Thank you!
