### ISSUE TITLE
FR: Log Parsing rule definitions support in Quickstarts

### ISSUE THREAD

**Issue by thezackm** [newrelic/newrelic-quickstarts#630]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Requesting support of adding Log Parsing definitions in quickstarts.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[Log Parsing Rules](https://docs.newrelic.com/docs/logs/ui-data/parsing/) have [Nerdgraph mutations available](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-log-parsing-rules-tutorial/#create-parsing-rules).

*As a user, I need to have pre-built parsing rules applied to the log data I send to New Relic from common situations and use-cases that enhance the value of my logs telemetry by adding fields for better searching and faceting.*

Example: 

*When I click to instrument and add dashboards for a quickstart with NPM data for my Cisco ASA firewalls; I expect to have pre-built parsing rules added as well so my syslog data is immediately valuable to me.*

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

New YAML standard for outlining the required fields on a parsing rule

```graphql
    rule: {
      description: "example parsing rule"
      enabled: false
      grok: "sampleattribute=%{NUMBER:test:int}"
      lucene: "logtype:testLogs"
      nrql: "SELECT * FROM Log WHERE `logtype` = 'testLogs'"
    }
```

```yaml
rules:
  - description: 
      enabled: 
      grok:
      lucene: 
      nrql: 
```

Note: there is an open ticket in the logs team to remove the requirement for the `NRQL` field here, FYI

cc: @jpvajda

**Comment by jpvajda** [comment]
@thezackm Are there particular quickstarts that would benefit from this feature? Which ones come to mind off the top of your head?

**Comment by jpvajda** [comment]
@thezackm do we have any customer references asking for this feature?

**Comment by lchapman4** [comment]
@jpvajda 

We've had several requests since NR Logs was released. As a follow-up to Zack's PR here, my colleague Marcel and I would like to submit default parsing patterns for our OHIs.  

In general, this would allow engineers in the field to submit parsing patterns for other data sources on behalf of customers and allow them to be shared. As it is today, when we create custom parsing for customers it stays with that customer and isn't shared with the rest of the field or other customers.

**Comment by thezackm** [comment]
commenting to appease the stale-bot overlords

**Comment by jpvajda** [comment]
@thezackm  🤖 🤖 🙏

**Comment by seemantk** [comment]
@lchapman4 @thezackm this just came across my radar screen.  How can we proceed with making this happen?
