### ISSUE TITLE
[Repo Rearchitecture] Add PR Validation check for ids in new quickstarts 

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#634]
### Description

When creating new quickstarts, a lot of contributors include `id` fields in the `config.yml`, usually copy/pasted from other quickstarts. This leads to duplicate id's and we currently have to manually check for these during PR review. We should add a PR validation check that identifies whether a quickstart is new and fails if the `config.yml` contains an `id` field, with appropriate instructions for the user. 

Virtuoso have confirmed that NerdGraph validation will not be able to identify if a quickstart is new or not so the check can't be done on that side.

This check should be performed before the NerdGraph validation check.

### Acceptance Criteria

 - [ ] Create a new workflow job that checks whether a quickstart is new or updated
 - [ ] Checks whether a new quickstart has an `id` field provided
      - [ ] If it does, fail with appropriate instructions for the user
 - [ ] Checks to make sure an updated quickstart still has an `id` field
 - [ ] Includes tests

**Comment by jpvajda** [comment]
@rudouglas , I was speaking to @jerelmiller about this ticket as DevEx is taking on some of our repo-re architecture work next sprint as they have bandwidth 🥳 . I was curious why is this tagged as a re-arch ticket? [Don't we already check for uniquessness? ](https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/check_quickstart_uniqueness.js
l)

**Comment by jpvajda** [comment]
I believe this is a duplicate so closing, unless @rudouglas objects.
