### ISSUE TITLE
[Repo Rearchitecture] Use new service to create/update Install Plans

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#636]
### Description

We will need to use the new service to create/update install plans based on contributions. This will require a new Job and script. We need to submit the install plan to `nr1CatalogSubmitInstallPlanStep`, we don't need to worry about separate jobs for create/update as this will be handled under the hood in the service.

### Acceptance Criteria 

> deletion of install plans is not in scope as deleting anything from the quickstart catalog isn't currently supported. 

- [ ] DevEx will have a [fork](https://github.com/newrelic/newrelic-quickstarts/pull/665 this functionality we want to confirm is available prior to starting this work.
- [ ] Create a new Job in the [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/e4ae0a4b5a10fb2da9de324ffdfae8cbbcd206c7/.github/workflows/release.yml) that runs a new script to submit the install plan to `nr1CatalogSubmitInstallPlanStep`
 - [ ] Should send the configuration details to the new NerdGraph mutation endpoint
 - [ ] Should handle errors returned from the service
 - [ ] Should include unit tests

We will also need to take into account our 3 environments which will need to be released at the same time:
 - EU Production
 - Production
 - Staging

#### Helpful Links

Schema - https://docs.google.com/spreadsheets/d/1EmAvq4kJUUPlpvJZ-s23uKDk_KCws9VgHzG1bJtwE4Y/edit#gid=0
NerdGraph - https://api.newrelic.com/graphiql?#query=mutation%20%7B%0A%20%20nr1CatalogSubmitMetadata%0A%7D%0A
DevEx Service - https://source.datanerd.us/nr1-dev-experience/catalog-service-elixir

**Comment by jpvajda** [comment]
From this [comment](https://github.com/newrelic/newrelic-quickstarts/issues/631#issuecomment-992745503) it sounds like there are few changes to the approach @rudouglas

**Comment by jerelmiller** [comment]
To make this concrete:

This will use a single mutation. No need to distiguish between create/update. Since the client is generating the `id`, you can use the `nr1CatalogSubmitInstallPlanStep` mutation. We'll handle the create or update under the hood.

**Comment by jpvajda** [comment]
I confirmed with @jerelmiller, this isn't blocked. 

_We should be ok to finish all work on DevEn side regardless of the status of the service, as long as we don’t yet switch to using the service as the primary means of deploying/validating_
