### ISSUE TITLE
[Repo Rearchitecture] Check that an install plan exists

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#637]
### Description

When a contributor defines an `Install Plan` in a quickstarts `config.yml` ([example](https://github.com/newrelic/newrelic-quickstarts/blob/2bc3a203b14826fde4c2bfa99ad33a3cf19113ca/quickstarts/gatsby-build/config.yml#L35)), we currently have to manually check whether that install plan exists yet or not and provide feedback to the user, so it would be great to automate this check.

We could use the information from the repo's [install](https://github.com/newrelic/newrelic-quickstarts/tree/main/install) directory, but I think if NerdGraph is now our single source of truth the check should be run against it to make sure. 

### Acceptance Criteria

 - [x] Create a new workflow job that runs on a PR in [validate_packs](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)
 - [x] Write a script that checks for install plans defined in a quickstarts `config.yml`, and validates they exist in ~NerdGraph~ the repo
 - [x] Handle errors returned to tell the user what action to take
 - [x] Include Unit Tests

**Comment by tyreer** [comment]
Note for DevEx: NerdGraph will expose this value as the `id` of a `step`. You can check out [a query like this](https://api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20nr1Catalog%20%7B%0A%20%20%20%20%20%20quickstarts%20%7B%0A%20%20%20%20%20%20%20%20results%20%7B%0A%20%20%20%20%20%20%20%20%20%20metadata%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20installer%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Nr1CatalogInstallPlan%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20steps%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

```
{
  actor {
    nr1Catalog {
      quickstarts {
        results {
          metadata {
            installer {
              ... on Nr1CatalogInstallPlan {
                steps {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jerelmiller** [comment]
I'll add the caveat that with that query, we'd only be able to check for _used_ install plans, which may or may not be a subset of all created install plans. If an install plan were created and merged, but no quickstarts yet integrate with it, we would not be able to detect that using NerdGraph.

We have 1 of 2 options to consider:

1) Add an additional field(s) to our NerdGraph schema to allow you to query for install plans
2) Do that check in the repo itself by analyzing all files to see if another uses that ID
