### ISSUE TITLE
[Repo Rearchitecture] Remove redundant validation after migration is complete

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#668]
## Summary
Once the repository has been migrated over to using Nerdgraph for validation and publishing, we will need to remove some of the old validation. 

Validation to remove:
* Remove `ensure-schema-compliance`
  * Note: Keep any validation around images and logos 
* Remove name uniqueness check

## AC
- [x] Redundant jobs/checks are removed

**Comment by jpvajda** [comment]
We will wait until we fully cut over to do this work.

**Comment by jpvajda** [comment]
moving to sustaining as it's something we need to wait on.
