### ISSUE TITLE
Automation: Check pack content for offensive language

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#67]
# Summary
We need to verify that there aren't any bad words getting into the repository. To do this we will be adding job to the `validate-packs` workflow to parse the packs for any bad language.

### Acceptance Criteria
- [ ] There is a new job that checks the packs for bad words and fails if any are found
- [ ] Name this job `offensive-language`
- [ ] Failure output is informative enough that contributors can easily find and fix any problematic language
- [ ] Workflow documentation is updated
- [ ] Check all files in the pack directory for bad words. (_for now_)

**Comment by jpvajda** [comment]
Due to the [Scunthorpe problem](https://en.m.wikipedia.org/wiki/Scunthorpe_problem) in implementing this type of check we will hold off for now, as all PRs will be reviewed by humans for our initial release.

**Comment by jpvajda** [comment]
due to the amount of reviewers of quickstarts, I feel we can close this for now and revisit if we find it's an actual problem.
