### ISSUE TITLE
[Repo Rearchitecture] Review and merge DevEx fork for quickstart validations

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#670]
## Summary
After DevEx finishes the work for validating quickstarts against nerdgraph, we will need to sit down and review the changes with them before merging.

* [Fork PR](https://github.com/newrelic/newrelic-quickstarts/pull/665/files)
## Acceptance Criteria 

- [x] Work is handed off to the DevEn team
- [ ] Work is merged into `main`

**Comment by nr-kkenney** [comment]
didn't realize we also had this ticket 🙈 

as an update, the PR is mostly good. the one thing we didn't realize was that the current workflow doesn't work correctly for contributions from forks. secrets are not available, so we can't call the api (as part of `pull_request` trigger) when the contribution comes from a fork.

this means we have to evaluate a different way to move forward. additionally, it seems that no matter what route we choose, we can't get everything we want currently 🙈 

something has to be sacrificed in order for us to move forward

**Comment by nr-kkenney** [comment]
we were on board to try using `workflow_run` and having a workflow trigger another workflow. i've implemented that change here: https://github.com/newrelic/newrelic-quickstarts/pull/665/commits/b50e12608e67f8f2d3714a5bf7445a7c562f455b.
