### ISSUE TITLE
[Repository] Deleting quickstarts and components documentation and checks

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#673]
### Relates to

`JIRA: DEVEX-2231` - `proposed`

### Background 

In this PR #661 we had a change to delete a quickstart which lead us to this issue. 

> Currently the following deletion functionality is available.

- the removal of a dashboard or an alert via a deletion would remove it from the quickstart. 
- the removal of an entire quickstart is not yet supported, since there's no corresponding mutation available for this operation.
- But we can manually delete the quickstart from the DB if necessary (_using old fashioned SQL_).

### Acceptance Criteria 

- [ ] Document the deletion process in our contributor guide to explain to contributors how deletions work.  
- [ ] Add a label to a PR that is attempting to do this: `quickstart deletion`
- [ ] Any PR in which attempts to delete a quickstart's config.yml file or the entire directory would then have this labeled applied. 
- [ ] follow up with DevEx on our approach due to the lack of a deletion mutation.

**Comment by aswanson-nr** [comment]
@jpvajda What should the check do? My first thought is that it should add a label to the pull request. I don't think a failed/succeeded check really helps this use case.

**Comment by jpvajda** [comment]
@aswanson-nr that could work, I think we just need to be made aware when an entire quickstart is being related.
