### ISSUE TITLE
[Repo Rearchitecture] Remove semantic release and conventional commits when re-architecture is complete

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#693]
## Description

`NOTE:` This should only be done when we have fully moved to the new architecture, using Nerdgraph exclusively, and the OILS service no longer needs releases.

You can reference this PR which already completed some of this work:
https://github.com/newrelic/newrelic-quickstarts/pull/681/files

## Acceptance Criteria
* [x] Remove conventional commit code from the [validate-packs workflow](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml)
* [x] Remove semantic release configuration and job from the [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/release.yml) workflow
* [x] Remove all semantic release and conventional commit configuration files
* [x] update contributing guide and readme, etc and remove the mention of conventional commits.

**Comment by zstix** [comment]
We will need to wait on this until the feature flag for all request to go to the Catalog API (and related database).
