### ISSUE TITLE
[Repo Rearchitecture] Ignore install plan id errors for quickstart validation

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#702]
## Description
If a PR comes in that creates a new quickstart and its associated install plan, the API will return a validation error for the quickstart saying that the install plan id is invalid. This is because the install does not exist yet in the database. Luckily, we have a workaround with the `validate install plans id` workflow that checks the local filesystem to ensure that referenced install plans exist. So, now that we are sure that the install plan and quickstart are valid when all the workflows pass, we need to not fail the API validation on a `invalid install plan id` error.

## Helpful links
- [Validate install plan ids workflow](https://github.com/tyreer/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml#L97-L117)
- [Validate quickstart pr workflow](https://github.com/tyreer/newrelic-quickstarts/blob/main/.github/workflows/validate_packs.yml#L6-L31)
- [Current error handling](https://github.com/tyreer/newrelic-quickstarts/blob/main/utils/nr-graphql-helpers.js#L58-L77)

## AC
- [x] The `validate pr quickstart` workflow ignores the install plan id error (it should still be printed to the console, but shouldn't fail the workflow)
- [x] Add tests for this case

**Comment by nr-kkenney** [comment]
for the moment this is blocked by: `nr1-dev-experience/catalog-service-elixir/pull/178` which has the changes that validate install plan ids.

interestingly enough, with the current feature branch and validation we currently have (or dont have) --  this whole workflow is working as expected 🙈

**Comment by nr-kkenney** [comment]
and we're unblocked 👍
