### ISSUE TITLE
[Repo Rearchitecture] Update field names to conform to Nerdgraph schema

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#703]
## Related PR 

https://github.com/newrelic/newrelic-quickstarts/issues/629

## Description
**Note**: This can be completed after the rest of this epic has been merged
Some fields have changed names in the graphql schema, this ticket is for going in and updating the yaml files to use these new field names. The validation and submission code already converts these fields over to their graphql equivalent. 

### Fields to update
- Main config: `logo` -> `icon`
- Alert config: `details` -> `description`

## AC

- [x] review Ru's PRs for reference
- [ ] Pause the merging of quickstarts PRs until this work is done
- [x] All quickstart yaml files use the `icon` field instead of `logo`
- [x] All alert yaml files use `description` instead of `details` 
- [x] All validation/submission scripts handle these new field names 
- [x] Ensure all documentation is updated in our [auto generated docs](https://github.com/newrelic/newrelic-quickstarts/issues/629) & [contributing guide](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#logos)

**Comment by jpvajda** [comment]
Before we merge this in, we may want to ensure we don't have any inflight PRs where a user has provided a logo file, or at least we'll want to be proactive and communicate they should change their quickstart to reference icons instead of logos.

**Comment by jerelmiller** [comment]
We'll also want to be careful to do this after the catalog service is using its db as the source of truth. Since its still proxing from OILS, its possible OILS may not know about the name changes, so we'll want to make sure that continues to function.

**Comment by zstix** [comment]
We've closed the PR for now, but the work that was done is on the following branch: `ru/updates`
