### ISSUE TITLE
DNN Evoq improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#709]
This [quickstart](https://developer.newrelic.com/instant-observability/dnn-evoq/82672f5f-48ec-477c-ae49-7eb24a91595f/) is lacking in dashboards and alerts and due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality.

### Justification

These are pages that are getting traffic or have high search

### Acceptance Criteria 

- [ ] add at least one dashboard
- [ ] add at least one alert

**Comment by seemantk** [comment]
I'll discuss with @mdumpati

**Comment by seemantk** [comment]
I'll discuss with @mdumpati

**Comment by seemantk** [comment]
Following up here, @mdumpati's team will take this on during their regular activities next quarter
