### ISSUE TITLE
Jumpstart quickstart has invalid configuration

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/newrelic-quickstarts#718]
## Description

I am working on some small fixes to our service's migration script to bring in all quickstarts to our database. Our service handles validation on all raw configuration for alerts and dashboards as well.

I'm running into errors importing a particular quickstart into the system, the [`Jumpstart quickstart`](https://developer.newrelic.com/instant-observability/jumpstart-quickstart/fbca935b-5a3e-41d7-b708-c24d90fcd820/). It's got some invalid alert configuration preventing me from importing it because it uses a union for all of the enum fields.

For example, I see [`baselineDirection`](https://github.com/newrelic/newrelic-quickstarts/blob/main/quickstarts/jumpstart/alerts/baseline-alert.yml#L19) set to this: `LOWER_ONLY | UPPER_AND_LOWER | UPPER_ONLY`. This is invalid because it must be 1 of those values, but not all 3. This is true for any of the fields that have that union operator in this alert configuration.

I do see this quickstart included in [public I/O](https://developer.newrelic.com/instant-observability/jumpstart-quickstart/fbca935b-5a3e-41d7-b708-c24d90fcd820/) and the [product](https://onenr.io/0eqwyXE6eQn). Looking further at it, it looks like its supposed to serve as an example for other quickstarts to follow, which is nice, but we currently have no way of making this distinction in the system. This is problematic because if a user actually thinks this is a valid quickstart and goes to try and install this quickstart, it will quickly fail as the alert configuration is totally invalid.

My question is: Do we even want this in I/O to begin with? Seems like it might be better moved elsewhere in this repo to serve as a template for other quickstarts, but its not a great quickstart itself.

If the intention is to keep it, then we are going to need some special logic to flag this as an example and provide some UX around this so that we don't allow a user to get partway through a quickstart install only for it to fail. If I were a user, I'd walk away unimpressed as to why the demo quickstart was unable to be successfully installed.

I could ignore this quickstart during the migration, but this will only last until someone changes it again. As soon as that example quickstart is updated, it will be marked invalid and will not be allowed to be merged. I'd love to discuss further how we should handle this as this is problematic.

**Comment by jpvajda** [comment]
@jcountsNR 👋
