### ISSUE TITLE
AWS Lambda Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#769]
This [quickstart](https://developer.newrelic.com/instant-observability/aws-lambda/6908e6c3-fed5-4c6c-a3fc-f85e467cefa1/) is lacking in dashboards and alerts and due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality.

### Justification

These are pages that are getting traffic or have high search

### Acceptance Criteria 

- [x] add at least 1 - 2 new dashboards
- [x] add at least 1 - 2 alerts

**Comment by EmilHammarstrand** [comment]
This quickstart has been done.
