### ISSUE TITLE
AWS RDS Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#772]
This [quickstart](https://developer.newrelic.com/instant-observability/aws-rds/4f6d6f0c-a258-4c5f-9d0f-9820c3067a51/) is lacking in dashboards and alerts and due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality.

### Justification

These are pages that are getting traffic or have high search

### Acceptance Criteria 

- [x] add at least 1 - 2 new dashboards
- [x] add at least 1 - 2 alerts

**Comment by EmilHammarstrand** [comment]
This quickstart has been done.
