### ISSUE TITLE
AWS SQS Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#775]
This [quickstart](https://developer.newrelic.com/instant-observability/aws-sqs/ef58d468-bcee-4a66-a641-8ff5453b5363/) is lacking in dashboards and alerts and due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality.

### Justification

These are pages that are getting traffic or have high search

### Acceptance Criteria 

- [ ] add at least 1 - 2 new dashboards
- [ ] add at least 1 - 2 alerts

**Comment by EmilHammarstrand** [comment]
This quickstart has been done.
