### ISSUE TITLE
[Repository] Quickstart schema validation does not report back on failure

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#819]
## Description
The schema validation job in the `Validate quickstarts` workflow is not reporting failure back to the pull requests that trigger it. On success, it reports back just fine.
None of the other jobs in this workflow appear to have this issue.

## Steps to Reproduce
1. Make a change to quickstart that would make it invalid
2. Create a pull request
3. Wait for the automation to run
4. Notice that the pull request shows that it's green and good to merge
5. Check the `Actions` tab for the repository and notice that there was an error

## Expected Behavior
Failure is reported back to the pull request so the contributor knows that changes are needed

## Example
* [PR](https://github.com/newrelic/newrelic-quickstarts/pull/818)
* [Failed job](https://github.com/newrelic/newrelic-quickstarts/runs/5146603741?check_suite_focus=true)

**Comment by aswanson-nr** [comment]
In the process of investigating this issue, I noticed that all the jobs will fail to report back if any of the "helper" (like node setup) error out. I'm going to update all the steps that report status back to the original PR to use the [job status](https://docs.github.com/en/actions/learn-github-actions/contexts#job-context) instead. That way any failures at any point in a job will be reported back to the PR. @nr-kkenney Does that seem like a good approach?

**Comment by nr-kkenney** [comment]
@aswanson-nr makes sense to me 👍
