### ISSUE TITLE
[Repository] Direct quickstart submissions to region-specific locations

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#825]
We need to Point quickstart submissions to eu, staging, and prod as currently all  submissions are pointing to staging) No rush for this yet, but might be good to set up sooner rather than later

### Questions 

- Do we have an EU team account? I don’t think so
- We will need an EU feature flag before we can set this up in that region, This should probably be a ticket

### Acceptance Criteria

- TBD

**Comment by jpvajda** [comment]
@aswanson-nr I think we took care of this recently, could you confirm?

**Comment by aswanson-nr** [comment]
@jpvajda , yep! this is totally done
