### ISSUE TITLE
MongoDB improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#842]
This [quickstart](https://newrelic.com/instant-observability/mongodb/6183e12f-a398-48e6-8431-a48db03e4443) is lacking in alerts and due to the interest in it from our customers we should add alerts to make this quickstart higher quality.

### Justification

These are pages that are getting traffic or have high search

### Acceptance Criteria 

- [ ] add at least 1 - 2 alerts

**Comment by seemantk** [comment]
I'm going to close this issue for now, but if we hear feedback from customers or field folks about it, we can reopen this.
