### ISSUE TITLE
[Reusable Workflow] Create a reusable workflow for Branch protection

### ISSUE THREAD

**Issue by rudouglas** [newrelic/newrelic-quickstarts#843]
## Description

Now that we have researched the benefits of reusable workflows we want to test this out on some higher priority items. We will create these at the repo level for now, and in the future discuss what workflows would benefit from living at the Org level.
See some additional details on the benefits [here](https://github.com/newrelic/docs-website/issues/5078#issuecomment-1039305342).

We use Branch Protection in 
 - [pr-merged.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/pr-merged.yml)
 - [release.yml](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/release.yml)

See instructions on how to create a Reusable Workflow [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows)

## Acceptance Criteria

 - [ ] Create a reusable workflow for Disabling Branch Protection 
 - [ ] Create a reusable workflow for Enabling Branch Protection 
 - [ ] Replace these jobs in the relevant workflows
 - [ ] Record any issues or pitfalls for future work

**Comment by jpvajda** [comment]
de-prioritized for a future sustaining epic.
