### ISSUE TITLE
[Repository] Release IQ quickstart errrors blocking PR merges

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#857]
Relates to:

https://github.com/newrelic/newrelic-quickstarts/pull/855
https://github.com/newrelic/newrelic-quickstarts/pull/845

### Issue 
A PR #855 is being blocked due to errors introduced in #845.  Though the Release IQ quickstart doesn't have more than 6 images, and these dashboard properties mentioned below don't really apply. 

### Expected 

We don't see these errors on #855 and the PR can be safely merged in and pass all checks. 

### Failures 
https://github.com/newrelic/newrelic-quickstarts/runs/5300104868?check_suite_focus=true

```
Error: quickstarts/releaseiq/dashboard/riq-dashboard.json
	 must have required property 'title'
	 must have required property 'level'
	 must have required property 'authors'
	 must have required property 'logo'
```

https://github.com/newrelic/newrelic-quickstarts/runs/5300104930?check_suite_focus=true

 Error: Each component should contain no more than 6 screenshots

```
  folder: '/home/runner/work/newrelic-quickstarts/newrelic-quickstarts/quickstarts/releaseiq',
  dashboardCount: 0,
  imageCount: 1,
  maxImages: 0
```

**Comment by jpvajda** [comment]
as a note all PRs in `To Review` are failing checks https://github.com/newrelic/newrelic-quickstarts/projects/3

**Comment by nr-kkenney** [comment]
i actually see the set of changes to make as already being made in an open pr: #856 

will merge that rather than making the changes.
