### ISSUE TITLE
[Dashboards] Enhance the quickstarts component custom viz to provide more directional metrics

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#883]
- [Related repo](https://github.com/rudouglas/quickstart-component-stats)
- Repo maintainer: @rudouglas 

### Problem

to decide what quickstarts are worth investing time and money to create or enhance requires a lot of manual research and decision making. It be cool if we had a quick and easy way to get directional data to answer this important question. 

### Preliminary questions to answer

- [x] What integrations does New relic support but are missing a quickstart?

> Defined in this G-Drive Doc: New Relic I/O -Quickstart plan.
> popular technologies with developers, like defined here: https://insights.stackoverflow.com/survey/2021?ref=thechiefio#technology

- [x] How do we define what quickstarts are worth investing time into creating? 
- [x] What data points can we use to provide directional guidance on what quickstarts should be built or enhanced?

**Data available in existing NR charts** 

* unique search terms
* clicks by quickstart
* clicks on view repo by quickstart
* docs tiles clicks by quickstart
*  page views per quickstart (Internal I/O)
* page views per quickstart (public catalog)

**SEO related metrics**

* Search Nuture Research  see `G:Drive: New Relic I/O | New Technologies` for an example of the data

**other data**

* requests from customers / users 
* available in other competitor marketplaces but missing from ours.

- [x] how would we aggregate these data to provide an easy metric to indicate where we should invest development time for quickstarts?

> If we take this data and generate a value on a scale of 1 - 100, where 100 is the highest and we should invest, and 1 is the lowest and we shouldn't bother investing time, 

### Acceptance Criteria

- [x] answer all questions above - @jpvajda 
- [ ] Move this repo from @rudouglas personal GH account to the [New Relic Experimental Org](https://github.com/newrelic-experimental). 
- [ ] Do a code review with the team for knowledge sharing
- [x] Consider the questions above and decide what data points we have that can be used to provide guidance on what quickstarts to invest in.
- [ ] enhance the custom viz to provide directional data.

**Comment by seemantk** [comment]
@rudouglas hi Ruari!  Is this ticket still  interesting for you?

**Comment by rudouglas** [comment]
Hey @seemantk i’m not sure if this viz is still being used at the minute, feel free to close this or if you’d like me to take a fresh look i’m happy to :D

**Comment by seemantk** [comment]
hi @rudouglas! thank you so much.  I'd love to take a fresh look at this, actually.
