### ISSUE TITLE
[Repository] Improve observability of workflows

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#892]
## Summary
The workflows that run on this repository have become much more important for the continued functionality of the quickstarts ecosystem. To support that we need to be able to track how often our workflow succeed, be notified when they fail, and have the information available to debug issues when they arise.

### What we want to know
- When validation/submission workflows run
- Whether they succeed or fail
- In the case of failure
  - Relevant information is reported to facilitate debugging 

### Ideas
- Error and info level logging
  - Forward logs to NR1? 
  - Logging library vs custom implementation
- Reporting workflow failure when it fails before the validation/submission step
  - Currently only reports failure if we get to that step and it fails
- Workflow runs as Transactions?

### Information to capture
- Workflow and job ids
- Time/date
- The quickstart or install plan that was being validated/submitted 
- The associated PR
-  Number of quickstarts or install plans being modified.
- For failure:
  - The contents of the graphql query
  - Associated error messages and codes

### Possible Solutions
* [Winston logger](https://www.npmjs.com/package/winston)
* [Winston to New Relic logs](https://www.npmjs.com/package/winston-to-newrelic-logs)
* [Manual Transactions](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-instrumentation/#background-txn)

### Acceptance Criteria

1. add extra logging to `stdout` and console log it.
2. remove the use of the APM agent for the repo, and use custom events & logs instead.
3. add an always running step at end of workflow to send status back to new relic.
5. validate this data is reporting into the NEW DevEn account
6. update dashboards that are keying off the APM events. [Quickstart repo workflows]()

**Comment by jpvajda** [comment]
we discussed this and decided to break it down into smaller steps, a first pass would be:

1. add logging to `stdout`
2. add an always running step at end of workflow to send status back to new relic.

**Comment by nr-kkenney** [comment]
this is just a general thought after some light thinking. for extra output for the future that we might want to log:

anything that would let us write/improve tests. as an example, we have functions validating graphql responses, etc. if we log what those responses are, we can then use that data in unit tests to catch errors in the future.

**Comment by nr-kkenney** [comment]
another thought:

for this workflow failure -- https://github.com/newrelic/newrelic-quickstarts/runs/5779399220?check_suite_focus=true -- we fail on the install plan step and dont get to the quickstart step.

if possible, it would be useful to know what install plans and quickstarts failed to submit / are blocked by this issue until its fixed. this would help us prioritize fixing the failure more appropriately.
