### ISSUE TITLE
[Repository] publish / validate script can take a quickstart name or id variable

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#894]
The publish/validate script would allow you to pass a quickstart name (or id)  into it. Then we would have an easy way to publish things manually as required.

### Acceptance Criteria 

- [ ] Determine the script should take an ID, or a quickstart name
- [ ] modify script to allow the variable to be passed through by a user
- [ ] When submitted, a quickstart then can be manually published.

**Comment by jpvajda** [comment]
@aswanson-nr 👋 I made this ticket per our convo on this idea, I was curious what scripts would need to be modified if we took this approach?

**Comment by jpvajda** [comment]
@aswanson-nr  this sounds like a duplicate of https://github.com/newrelic/newrelic-quickstarts/issues/931 can you confirm? if so I can close it out.

**Comment by aswanson-nr** [comment]
Definitely a dub, @jpvajda
