### ISSUE TITLE
Kubernetes Improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#908]
This [quickstart](https://newrelic.com/instant-observability/kubernetes/88a79f52-81c1-4fa2-99f8-3cb5b012f160/) is lacking in dashboards and alerts and due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality.

### Justification

We have an upcoming event (Kubecon) where this will be showcased

### Acceptance Criteria 

- [x] add at least one new dashboard
- [x] add at least one alert

**Comment by lazyplatypus** [comment]
What is the exact type of data that is missing in this quickstart? I can take this one but need to get more context on the customer requests! @jpvajda
