### ISSUE TITLE
Prometheus Openmetrics integration improvements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#914]
This [quickstart](https://newrelic.com/instant-observability/prometheus-openmetrics/d7db4b03-f2a6-4282-b9e7-90bbfdaa0e8d/) is lacking in dashboards and alerts and doesn't have an install plan.  Due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality. 

### Justification

We have an upcoming event (Kubecon) where this will be showcased

### Acceptance Criteria 

- [ ] add at least one new dashboard
- [ ] add at least one alert
- [ ] use this install plan for [pomi](https://github.com/newrelic/newrelic-quickstarts/tree/main/install/pomi)

**Comment by jpvajda** [comment]
For the 3rd AC, I am confirming our approach with a few I/O teams, so that is something that is currently a work in progress how we'll solve that.

**Comment by shawnj** [comment]
@jpvajda FYI: I did create a Prometheus OpenMetrics Integration (POMI) install plan for use with the ArgoCD quickstart.

**Comment by jpvajda** [comment]
@shawnj Great! Thank you

**Comment by jpvajda** [comment]
@shawnj quick question, which one should this quickstart use? Also should POMI be moved under this directory? for [open source monitoring](https://github.com/newrelic/newrelic-quickstarts/tree/main/install/open-source-monitoring)

**Comment by shawnj** [comment]
@jpvajda It could be moved under Open Source Monitoring but we manage the underlying containers/application that supports  POMI. Its open sourced but managed by NR...so I'm not sure.  That might be fine to move it so that the POMI and Prometheus are under the same header.

**Comment by shawnj** [comment]
@jpvajda Also, anything for Prometheus OpenMetric Integration shouldn't use Prometheus Remote-Write integrations install option.  Two different usage targets.
