### ISSUE TITLE
Create an Istio quickstart

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#917]
[istio](https://istio.io/) would make a good quickstart addition to the catalog. 

Istio extends Kubernetes to establish a programmable, application-aware network using the powerful Envoy service proxy. Working with both Kubernetes and traditional workloads, Istio brings standard, universal traffic management, telemetry, and security to complex deployments.

### Acceptance Criteria

- [x] create a new directory for Istio
- [x] Add an install plan Or use this one [kubernetes-install](https://github.com/newrelic/newrelic-quickstarts/blob/main/install/guided-install/kubernetes/install.yml)?
- [x] Add at least 1 dashboard
- [x] Add at least 1 alert
- [x] Write good summary and descriptions defining this quickstart

**Comment by shawnj** [comment]
Might not need an install plan.  If the Prometheus integration (POMI) is installed with the nri bundle in Kubernetes, it will automatically pick up the Istio metrics. That is if Istio was installed using the default method of the `istioctl` cli.

**Comment by jpvajda** [comment]
@shawnj thanks for taken this on! When you have a PR to review if you can link it to this issue that be excellent. 

you can either click on the `Development` menu item 👉  in the side bar and link the PR, or just added the keyword `fixes` and the link to the PR in the description of this issue and it will auto-link it
