### ISSUE TITLE
Prometheus Remote Write Integration

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#918]
This [quickstart](https://newrelic.com/instant-observability/prometheus-remote-write/7dbd7355-c380-4211-bd32-fed9a65351af) is lacking in dashboards and alerts and doesn't have an install plan.  Due to the interest in it from our customers we should add a dashboard an alert to make this quickstart higher quality. 

### Justification

We have an upcoming event (Kubecon) where this will be showcased

### Acceptance Criteria 

- [ ] add at least one new dashboard
- [ ] add at least one alert
- [ ] use this install plan for [prometheus](https://github.com/newrelic/newrelic-quickstarts/blob/main/install/open-source-monitoring/prometheus/install.yml)

**Comment by jpvajda** [comment]
For the 3rd AC, I am confirming our approach with a few I/O teams, so that is something that is currently a work in progress how we'll solve that.

**Comment by tclayton-newr** [comment]
I have added a dashboard for getting users started with monitoring their own Prometheus instance. The install plan I don't _think_ adds that for users at the moment since the link takes users directly to configuring their remote write integration.

**Comment by jpvajda** [comment]
@tclayton-newr yes, that's a limitation we have due to how we are trying to leverage the existing AMD workflows, let me ask the DevEx team if there is anyway to get the dashboards to install for the user using this flow.

**Comment by jpvajda** [comment]
@tclayton-newr so this flow should allow the user to install the dashboards and alerts, the workflow follows our ruby quickstart install flow, which you can see by attempting to install Ruby on a new relic account, essentially a user is taken back to the install plan flow to finish the final step, after the finish the setup in the AMD nerdlet.

I'd suggest finishing one of these prometheus quickstarts and merging it, then we can test the flow to ensure the install plan is doing what we expect. 



**User starts here:**
<img width="1063" alt="Screen Shot 2022-03-17 at 11 21 41 AM" src="https://user-images.githubusercontent.com/1395158/158858355-d4ba858a-451b-4fc7-9439-82903decdc20.png">

**on begin of click installation they go here**
<img width="1542" alt="Screen Shot 2022-03-17 at 11 20 25 AM" src="https://user-images.githubusercontent.com/1395158/158858359-be97f32f-a86d-4112-90d6-506a3abc78af.png">

**User finishes here:**
<img width="1063" alt="Screen Shot 2022-03-17 at 11 21 41 AM" src="https://user-images.githubusercontent.com/1395158/158858355-d4ba858a-451b-4fc7-9439-82903decdc20.png">

**Comment by tclayton-newr** [comment]
That's awesome! I'll have a look at running that from the new onboarding experience.

**Comment by jpvajda** [comment]
@tclayton-newr yeah, it be really great to test this flow after we merge in this PR, sometimes the intended flow, isn't what we expected, so testing it out would be a fantastic idea.

**Comment by tclayton-newr** [comment]
I tested this some time ago and forgot to report back here 😛 
The installation flow is there via the quickstart but it still leaves some things to be desired. Since the changes would have to be made internal to NR, I think it would be okay to close this ticket out. 

To summarize, you currently have to close the integration install pane via the ❌ in the top right, which is not intuitive for new users. 
![image](https://user-images.githubusercontent.com/87031785/175559646-06a7450f-a55c-489c-9c3d-1250b11a48d3.png)
