### ISSUE TITLE
Add functionality to manually publish a quickstart

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#931]
## Summary
Our current publishing workflows use the associated pull request to determine what needs to be published to nerdgraph. We would like the ability to trigger a workflow on demand to publish a single quickstart.

### Desired Behavior
* The workflow can be triggered just like any `workflow_dispatch` action
* The workflow takes in the quickstart id 
* The workflow takes in the install plan id 
* The workflow publishes the contents of that quickstart on the `main` branch to nerdgraph.
* The workflow publishes the  contents of the install plan on the `main` branch to nerdgraph.
* This workflow  can only be run by Admins of the repo.

### Helpful links
- [workflow dispatch trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)

## Acceptance Criteria 
 - [ ] the workflow for updating install plans can be dispatched manually
 - [ ] the workflow for updating quickstarts can be dispatched manually
 - [ ] both workflows take in the id of the install plan/quickstart and the region to publish (staging, prod, EU-prod)
 - [ ] both workflows use the install plan/quickstart on the `main` branch for publishing

**Comment by jpvajda** [comment]
@aswanson-nr will add some AC to this.

**Comment by jpvajda** [comment]
That's some fine AC. @aswanson-nr
