### ISSUE TITLE
[Repository] Research hosting image for quickstarts on a CDN

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#933]
We currently host all our image files used for quickstarts on github which acts as a "CDN" for us. Though this may not be the best use of Github and could cause issues rendering image files such as logos, dashboards, etc as we scale the amount of quickstarts we have in our ecosystem.

### Acceptance Criteria

- [ ] Consider at what point should we introduce a CDN to store these image files instead of hosting them on Github
- [ ] Consider what CDN we'd use
- [ ] Estimate the effort to do this work.

**Comment by jerelmiller** [comment]
The catalog service handles uploading nerdpack screenshots currently. Perhaps this is something we should consider for quickstarts as well?

**Comment by jpvajda** [comment]
@jerelmiller yeah, perhaps. Where do we host those?

**Comment by jerelmiller** [comment]
AWS
