### ISSUE TITLE
[Repository] Explore changes to quickstart submission

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/newrelic-quickstarts#934]
## Summary
We ran into a few failures documented [here](https://github.com/newrelic/newrelic-quickstarts/issues/881). One of the observations we made was that when a workflow fails to submit quickstarts for the staging environment, production and EU are both skipped.

Additionally, if we fail for any environment, when we need to rerun the workflow, all environments are included. So we fail for the EU environment, we rerun EU, staging, production -- but we just want to rerun EU.

We want to try answer the following questions:
- should quickstarts be submitted across all environments in parallel? is there a reason to go to staging first, then maybe EU, prod in parallel?
- can we set up the workflow(s) so that these are separate, with the ability to pass/fail independently of another environment?

## Acceptance Criteria
- [x] set up the workflow(s) so that these are separate, with the ability to pass/fail independently of another environment
- [x] a workflow can be manually run for each environment as needed.

**Comment by jerelmiller** [comment]
I could see prod and EU being run in parallel. One advantage of running staging first is that you can catch any issues you may see before it hits prod/EU. That may or may not be enough of a reason to not make that parallel as well, but wanted to throw that out there as a potential reason to keep staging first.

**Comment by nr-kkenney** [comment]
ive been testing out most of my changes on a fork / personal repository. i now have the workflow(s) set up, and the summary looks like:

![Screen Shot 2022-04-06 at 4 54 21 PM](https://user-images.githubusercontent.com/70179215/162093497-a5e005f6-9112-4cc6-a1ab-c7445a2f776a.png)

a slight bit of testing is still needed, but should be able to get a PR out tomorrow.

**Comment by nr-kkenney** [comment]
With how i set things up, having the validation workflows use the reusable workflow would be a bit messy. The reusable workflow does both install plan & quickstart stuff in one run. The validation we currently have in the repo is separate for install plans & quickstarts, with no clean way to use the reusable workflow.

Additionally, the validation workflows actually have more jobs than the reusable workflow does -- they are validating multiple things, sometimes using many scripts. The reusable workflow only validates against the API (schema validation).

I could setup two reusable workflows — one for install plans, one for quickstarts — but i actually think we dont want this, since it might be on the table to actually just have one entrypoint script in the future — the CLI.
