### ISSUE TITLE
[Repository] Incorrect dashboard screenshots appearing in I/O

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-quickstarts#939]
## Description
All the screenshots in the `/dashboard` directory for a quickstart are being uploaded as the screenshots for all the dashboards, instead of just the screenshots associated with a particular dashboard. this is resulting in duplicate dashboards being shown to the user in the external and internal catalogs.

## Examples
- [Catchpoint quickstart](https://newrelic.com/instant-observability/catchpoint-quickstart/ac2341e3-05bb-49c5-b445-b16b27fc6ea0)
- [Battlesnake quickstart](https://newrelic.com/instant-observability/battlesnake/63a65857-a25e-4654-9174-928e5894b3b9)
-  could be more.. 🤔 

<img width="1822" alt="Screen Shot 2022-03-21 at 10 42 27 AM" src="https://user-images.githubusercontent.com/1395158/159311916-30047e42-5ea8-4a10-9f77-4dfb9cee945b.png">

## Code
* [The code that grabs screenshots](https://github.com/newrelic/newrelic-quickstarts/blob/72ee0229e8c4e709553158ffedd02a58489141ac/utils/create_validate_pr_quickstarts.js#L298-L304)

## AC
- [ ] obtain a list of quickstarts with more than 1 dashboard to verify screen shots are rendering correctly after this change.
- [ ] obtain a list of quickstarts that have the incorrect naming convention being used, as those would also break with this change.
- [ ] Only the screenshots associated with a particular dashboards are visible. 
- [ ] Update documentation to explain what a contributor needs to do when naming dashboards in this new convention.
- [ ]  this change should have no impact on future PRs for quickstarts that have new dashboards added.

**Comment by aswanson-nr** [comment]
- Moving dashboards into their own directory
- For quickstarts with one dashboard, do we want to move those to their own directory? Yes
  - E.g. /dotnet/dashboards/dotnet/thing.json
  - This would require automation (touches all quickstarts)
- This aligns with the future of the repository
  - Vs. /dotnet/dashboards/thing.json
- This could be done manually (only 8 quickstarts)
- What do we need to update for this change?
  - Workflow to validate / submit
  - Workflow that checks image counts
  - Tests for the workflow
  - Update contributor docs
  - Update all the quickstarts via a script (see above)

**Comment by aswanson-nr** [comment]
Quickstarts with more than 1 dashboard:
|name|dashboard count|
|-|-|
|infrastructure-integrations-data-analysis|5|
|catchpoint|4|
|browser|4|
|lacework|3|
|battlesnake|3|
|oma-data-gov|2|
|kentik|2|
|heroku|2|

**Comment by tabathadelane** [comment]
I updated the `CONTRIBUTING.md` and manually moved the dashboards listed above in the [forked repo](https://github.com/aswanson-nr/newrelic-quickstarts). I also ran the script to move the remaining `272` dashboards into their own directories in my last commit.
