### ISSUE TITLE
Add a CoreDNS quickstart

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#955]
[CoreDNS](https://coredns.io/) would make a good quickstart addition to the catalog. 

Core[DNS](https://en.wikipedia.org/wiki/Domain_Name_System) is a DNS server. It is written in [Go](https://golang.org/). It can be used in a multitude of environments because of its flexibility. CoreDNS is licensed under the [Apache License Version 2](http://www.apache.org/licenses/LICENSE-2.0), and completely open source.
Development takes place on [Github](https://github.com/coredns/coredns). Some devs hang out on [Slack](https://slack.cncf.io/) on the #coredns channel.

### Acceptance Criteria

- [ ] create a new directory for Core DNS
- [ ] Add an install plan 
- [ ] Add at least 1 dashboard
- [ ] Add at least 1 alert
- [ ] Write good summary and descriptions defining this quickstart

**Comment by jpvajda** [comment]
@lazyplatypus 👋

**Comment by tclayton-newr** [comment]
Not sure if anyone else is actively working on this, but I'll be having a look within the next few days.

**Comment by jpvajda** [comment]
@tclayton-newr that be great, you may want to sync with @lazyplatypus on that work as he was also interested in this quickstart.
