### ISSUE TITLE
`title` field changes to quickstarts are overriding the `name` field for URLS

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#957]
### Related Issue

`DEVEX-2389`

### Issue

In this [PR](https://github.com/newrelic/newrelic-quickstarts/commit/369ae30f993a10ce9042c639985b496a3b511027) I changed the titles of several quickstarts that were using the term `quickstart` in their title, as that is a naming convention we don't want to use in the UI, however this seemed to change the URL structure of each quickstart. 

**Gigamon example**
```
Previous: 'https://newrelic.com/instant-observability/gigamon-newrelic/d6b36ecf-bf99-475c-938f-370153db8e70'
Now: 'https://newrelic.com/instant-observability/gigamon/d6b36ecf-bf99-475c-938f-370153db8e70'
```

The understanding was `name` defines the URL structure, not `title`, so it's not clear as to why this change impacted the URLS of these quickstarts

### Steps to reproduce

1. review this PR and look at the lines changed for Gigamon, Glassbox, catchpoint and notice the title field change
2. go to each of their respective i/o pages and see the URL is actually defined by the title field not the name field. 

- [gigamon](https://newrelic.com/instant-observability/gigamon/d6b36ecf-bf99-475c-938f-370153db8e70)
- [glassbox](https://newrelic.com/instant-observability/glassbox/bdb952f3-28db-4ee7-89c6-b00244b0bb73)
- [catchpoint](https://newrelic.com/instant-observability/catchpoint/ac2341e3-05bb-49c5-b445-b16b27fc6ea0)

3. to further prove that the title field is actually defining the URL see the jumpstart quickstart, which title is now [Jumpstart](https://newrelic.com/instant-observability/jumpstart-quickstart-tool/fbca935b-5a3e-41d7-b708-c24d90fcd820) quickstart tool, you can see that clearly this title change has impacted the URL string. 

### Quick fix ✅ 

- we fix this problem with gigamon be reverting the title changes back to the original form, as to not have broken links

### Logic fix ⚠️ 

Ensure the following is true: 

- name (slug) = URL
- title (displayName) = displaying in the UI only
- Change to the title should not impact change to the URL
- Consider if we can take this work on from DevEx, if they won't be putting the fix in anytime soon, as well as if we should change name to slug in the quickstart repo to align better with what fields exist in GraphQL

**Comment by jpvajda** [comment]
notes on short term fix:

- glassbox shouldn't be impacted as it's name field now matches it's title field so the URL should be the same.
- catchpoint did change, but it's not a partner quickstart so it should be ok until we figure out the logic issue
- I've changed gigamon to match title to name fields in this PR: #959

**Comment by aaronbassett** [comment]
Chatting with @jcountsNR and it appears this may also be impacting the [Netlify quickstart](https://newrelic.com/instant-observability/netlify/5861d7f5-26c0-43ad-bda8-c893c4b27b25)

We're also in the situation now where it appears that we have backlinks to both the `netlify` and `netlify-builds` URLs from external sites. Can we 301 redirect whichever URL is not going to be used going forward, please?

**Comment by jpvajda** [comment]
@aaronbassett 👋 yes sir, we are looking at this issue next sprint https://github.com/newrelic/instant-observability-website/issues/114

**Comment by jpvajda** [comment]
so we can't see the title change for `gigamon` even after doing a new build. Here is what is showing up in GraphQL

```
{
  "data": {
    "actor": {
      "nr1Catalog": {
        "quickstart": {
          "metadata": {
            "displayName": "gigamon-newrelic",
            "slug": "gigamonnewrelic"
          },
          "sourceUrl": "https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/gigamon"
        }
      }
    },
```

**Comment by jpvajda** [comment]
We are going to trigger an update to the site's quickstart JSON as we saw it wasn't updated[ since yesterday ](https://github.com/newrelic/instant-observability-website/commit/60a07984781e549aa20a4a322985292dedd78ce3)

**Comment by jpvajda** [comment]
so now we've updated the quickstart json and what we are seeing: 

the site [quickstart json](https://github.com/newrelic/instant-observability-website/blob/main/src/data/quickstarts.json) file has the following:

```
name: gigamonnewrelic
title: gigamon-newrelic
```

and the url of gigamon is https://newrelic.com/instant-observability/gigamonnewrelic/d6b36ecf-bf99-475c-938f-370153db8e70

and the[ quickstart config](https://github.com/newrelic/newrelic-quickstarts/blob/main/quickstarts/gigamon/config.yml) has the following:

```
id: d6b36ecf-bf99-475c-938f-370153db8e70
name: gigamon-newrelic
title: gigamon-newrelic
```

So there is a problem where GraphQL seems to be changing the Slug

```
{
  "data": {
    "actor": {
      "nr1Catalog": {
        "quickstart": {
          "metadata": {
            "displayName": "gigamon-newrelic",
            "slug": "gigamonnewrelic"
          },
          "sourceUrl": "https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/gigamon"
        }
      }
    },
```

**Comment by jpvajda** [comment]
DevEx confirmed 

That the title is used and slugified, so when a hyphen is present, it removes it. and when there is no hyphen, one is added. 

Our resolution was to change the title back to Gigamon Newrelic to allow the URL slug to be reverted back to it's original form. 

https://newrelic.com/instant-observability/gigamon-newrelic/d6b36ecf-bf99-475c-938f-370153db8e70

**Comment by josephgregoryii** [comment]
### Some takeaways from today
- When adding/updating a quickstart, adding a hyphen (`-`) will get removed after slugifying the name
- `name` is used for slug
- `title` seems to not be used at all (specifically for UI)
- for now, gigamon will have an odd title `Gigamon Newrelic`, due to slugify adding a hyphen if we change it to `Gigamon New Relic`

**Comment by jpvajda** [comment]
DevEx has a ticket now to resolve this `DEVEX-2389`

**Comment by jpvajda** [comment]
Consider if we can take this work on from DevEx, if they won't be putting the fix in anytime soon, as well as if we should change `name` to `slug` in the quickstart repo to align better with what fields exist in GraphQL

**Comment by jpvajda** [comment]
I'll close this issue and make a new one to account for the changes devex is making
