### ISSUE TITLE
[Content] Support the Dev Advocacy team as they improve our quickstart documentation

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-quickstarts#991]
relates to:
https://github.com/newrelic/newrelic-quickstarts/issues/875

### Acceptance Criteria

As the content team of @alexronquillo and @mehreentahir16  start drafting the content for how to contribute to quickstarts on the Dev Site DevEn will need to be available to support their questions.

- [ ] Answer any questions the content team has to help them document this process
- [ ] Ensure they are briefed on the changes that are occurring in the [repo restructure epic](https://github.com/newrelic/newrelic-quickstarts/issues/907)

**Comment by zstix** [comment]
We're working through how we would like to restructure the repository. It might make sense to wait on documenting this stuff until we know what this is going to look like.
